=== anyvalerie/intelliJ-idea-example/laba1.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT laba1 (house)*>
        <!ELEMENT house (home|apartament|office|debt)*>
        <!ELEMENT home (adress|numberofFloors|numberofEntrances|overallFlats|heating|gas)*>
        <!ELEMENT adress (#PCDATA)>
        <!ELEMENT numberofFloors (#PCDATA)>
        <!ELEMENT numberofEntrances (#PCDATA)>
        <!ELEMENT overallFlats (#PCDATA)>
        <!ELEMENT heating (#PCDATA)>
        <!ELEMENT gas (#PCDATA)>
        <!ATTLIST gas
                state CDATA #REQUIRED>
        <!ELEMENT apartament (numberofFlat|numberofEntrance|overallSquare|livingSquare|phone|tenant|StateApartament|privatizedApartament|departmentalApartament)*>
        <!ELEMENT numberofFlat (#PCDATA)>
        <!ELEMENT numberofEntrance (#PCDATA)>
        <!ELEMENT overallSquare (#PCDATA)>
        <!ELEMENT livingSquare (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ELEMENT tenant (#PCDATA)>
        <!ELEMENT StateApartament (numberOfTenants|paymentInMonth|benefits)*>
        <!ELEMENT numberOfTenants (#PCDATA)>
        <!ELEMENT paymentInMonth (#PCDATA)>
        <!ELEMENT benefits (#PCDATA)>
        <!ELEMENT office (#PCDATA)>
        <!ELEMENT debt (#PCDATA)>
        <!ELEMENT privatizedApartament (dateofPrivatization|numberofConract|paymentInYear)*>
        <!ELEMENT dateofPrivatization (#PCDATA)>
        <!ELEMENT numberofConract (#PCDATA)>
        <!ELEMENT paymentInYear (#PCDATA)>
        <!ELEMENT departmentalApartament (numberofTenants|nameofDepartmental|payment)*>
        <!ELEMENT numberofTenants (#PCDATA)>
        <!ELEMENT nameofDepartmental (#PCDATA)>
        <!ELEMENT payment (#PCDATA)>

=== anyvalerie/intelliJ-idea-example/laba1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE laba1 SYSTEM "laba1.dtd">
<laba1>
	<house>
			<home>
				<adress>Ladozhskaya</adress>
				<numberofFloors>9</numberofFloors>
				<numberofEntrances>3</numberofEntrances>
				<overallFlats>128</overallFlats>
				<heating>water</heating>
				<gas state="Y"/>
			</home>
		<apartament>
			<numberofFlat>117</numberofFlat>
			<numberofEntrance>3</numberofEntrance>
			<overallSquare>111,4</overallSquare>
			<livingSquare>95,6</livingSquare>
			<phone>Y</phone>
			<tenant>Glushko</tenant>
			<StateApartament>
				<numberOfTenants>4</numberOfTenants>
				<paymentInMonth>2000</paymentInMonth>
				<benefits>10</benefits>
			</StateApartament>
		</apartament>
		<office>Y</office>
		<debt>11000</debt>
	</house>
	<house>
		<apartament>
			<numberofFlat>12</numberofFlat>
			<numberofEntrance>1</numberofEntrance>
			<overallSquare>55,1</overallSquare>
			<livingSquare>40,2</livingSquare>
			<phone>Y</phone>
			<tenant>Guseva</tenant>
			<privatizedApartament>
				<dateofPrivatization>22-01-1997</dateofPrivatization>
				<numberofConract>11520</numberofConract>
				<paymentInYear>25000</paymentInYear>
			</privatizedApartament>
		</apartament>
		<home>
			<adress>Chuikova</adress>
			<numberofFloors>18</numberofFloors>
			<numberofEntrances>4</numberofEntrances>
			<overallFlats>150</overallFlats>
			<heating>air</heating>
			<gas state="Y"/>
		</home>
		<office>N</office>
		<debt>5010</debt>
	</house>
	<house>
		<apartament>
			<numberofFlat>125</numberofFlat>
			<numberofEntrance>5</numberofEntrance>
			<overallSquare>187,8</overallSquare>
			<livingSquare>169,3</livingSquare>
			<phone>N</phone>
			<tenant>Panasenko</tenant>
			<departmentalApartament>
				<numberofTenants>2</numberofTenants>
				<nameofDepartmental>MVD</nameofDepartmental>
				<payment>980</payment>
			</departmentalApartament>
		</apartament>
		<home>
			<adress>Borodinskaya</adress>
			<numberofFloors>1</numberofFloors>
			<numberofEntrances>8</numberofEntrances>
			<overallFlats>224</overallFlats>
			<heating>dynamic</heating>
			<gas state="N"/>
		</home>
		<office>Y</office>
		<debt>36458</debt>
	</house>
	<house>
		<apartament>
			<numberofFlat>25</numberofFlat>
			<numberofEntrance>1</numberofEntrance>
			<overallSquare>14,5</overallSquare>
			<livingSquare>13,7</livingSquare>
			<phone>N</phone>
			<tenant>Marufenko</tenant>
			<departmentalApartament>
				<numberofTenants>3</numberofTenants>
				<nameofDepartmental>FBI</nameofDepartmental>
				<payment>10258</payment>
			</departmentalApartament>
		</apartament>
		<office>Y</office>
		<debt>36458</debt>
	</house>
</laba1>
